@WebApi_HostAddress = http://localhost:5175

### GET all persons
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json
###

### CREATE PERSON
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Karol",
  "lastName": "Kopacz",
  "email": "karol@wsei.edu.pl",
  "phone": "48 123 456 789",
  "gender": 0
}

###

### GET PERSON BY ID
GET {{WebApi_HostAddress}}/api/contacts/fd70525e-e2ab-4c63-b236-07391b21640c
Accept: application/json


###

### UPDATE PERSON
PUT {{WebApi_HostAddress}}/api/contacts/fd70525e-e2ab-4c63-b236-07391b21640c
Content-Type: application/json

{
  "id": "fd70525e-e2ab-4c63-b236-07391b21640c",
  "firstName": "AdamTest",
  "lastName": "NowakTest",
  "email": "adam.updated@email.com",
  "phone": "999999999",
  "gender": 0
}
###

### Create Note
POST http://localhost:5175/api/contacts/fd70525e-e2ab-4c63-b236-07391b21640c/notes
Content-Type: application/json

{
  "content": "Pierwsza notatka"
}
###

###Delete
DELETE http://localhost:5175/api/contacts/fd70525e-e2ab-4c63-b236-07391b21640c/notes/48e48e59-0b92-4c14-897d-815e94f6e23b

###
GET http://localhost:5175/api/contacts
Accept: application/json


### Login
POST http://localhost:5175/api/auth/login
Content-Type: application/json

{
  "email": "jan.kowalski@crm.pl",
  "password": "Manager@123!"
}

### Get contacts without token
GET http://localhost:5175/api/contacts
Accept: application/json

### Get contacts with token
GET http://localhost:5175/api/contacts
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJmNTQ1NTc5Ni1hZWNkLTQ4YmEtOGY4MC1iNmYxNzMxMzE5YjgiLCJpYXQiOiIxNzc3NzIwMjExIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc3NzIwMjExLCJleHAiOjE3Nzc3MjM4MTEsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.WBbtRBBtBaGm3Hd-vXq9WO9rTTAS2l-xTZJt1ZFArGs

#
#
# 
# DO PROJEKTU    DO PROJEKTU DO    PROJEKTU DO    PROJEKTU DO    PROJEKTU DO     PROJEKTU DO     PROJEKTU
#
#
#
# Komendy do zresetowania bazy danych dla testów:
# dotnet ef database drop --project Infrastructure --startup-project WebAPI
# dotnet ef database update --project Infrastructure --startup-project WebAPI
#

@WebApi_HostAddress = http://localhost:5175
### Login
POST http://localhost:5175/api/auth/login
Content-Type: application/json

{
  "email": "jan.kowalski@crm.pl",
  "password": "Manager@123!"
}

### Import JSON Poprawne Rekordy
POST {{WebApi_HostAddress}}/api/contact-import
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJkOWRlMDE4ZC0wYTYzLTRhYjEtODc4ZC05ZTgxMDhhN2Q0YmYiLCJpYXQiOiIxNzc5OTkzOTk0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc5OTkzOTk0LCJleHAiOjE3Nzk5OTc1OTQsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.uWZRkDI1695tzOHqkA1VkhRWQBv0QtTWvfaIq3q4lkE
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="contacts-import.json"
Content-Type: application/json

< ./JsonImport.json
--boundary--


### Import JSON Niepoprawne Rekordy
POST {{WebApi_HostAddress}}/api/contact-import
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJkOWRlMDE4ZC0wYTYzLTRhYjEtODc4ZC05ZTgxMDhhN2Q0YmYiLCJpYXQiOiIxNzc5OTkzOTk0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc5OTkzOTk0LCJleHAiOjE3Nzk5OTc1OTQsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.uWZRkDI1695tzOHqkA1VkhRWQBv0QtTWvfaIq3q4lkE
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="contacts-import.json"
Content-Type: application/json

< ./JsonImportErrorTest.json
--boundary--


### Import CSV Poprawne Rekordy
POST {{WebApi_HostAddress}}/api/contact-import
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJkOWRlMDE4ZC0wYTYzLTRhYjEtODc4ZC05ZTgxMDhhN2Q0YmYiLCJpYXQiOiIxNzc5OTkzOTk0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc5OTkzOTk0LCJleHAiOjE3Nzk5OTc1OTQsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.uWZRkDI1695tzOHqkA1VkhRWQBv0QtTWvfaIq3q4lkE
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="contacts-import.csv"
Content-Type: text/csv

< ./CsvImport.csv
--boundary--

### Import CSV Niepoprawne Rekordy
POST {{WebApi_HostAddress}}/api/contact-import
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJhZWM2MzkzZC0yMjI2LTQ5ZGEtYjJjYi1lMmM1NmViOWNjYTkiLCJpYXQiOiIxNzc3NzIzNzY4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc3NzIzNzY4LCJleHAiOjE3Nzc3MjczNjgsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.xgB8jxWiSFSn_XJ4K8wkaeDSlqv-9FUNts4hcwO-9lE
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="contacts-import.csv"
Content-Type: text/csv

< ./CsvImportErrorTest.csv
--boundary--

### Csv Delimiter Test # | ;
POST {{WebApi_HostAddress}}/api/contact-import
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJkOWRlMDE4ZC0wYTYzLTRhYjEtODc4ZC05ZTgxMDhhN2Q0YmYiLCJpYXQiOiIxNzc5OTkzOTk0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc5OTkzOTk0LCJleHAiOjE3Nzk5OTc1OTQsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.uWZRkDI1695tzOHqkA1VkhRWQBv0QtTWvfaIq3q4lkE
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="contacts-import.csv"
Content-Type: text/csv

< ./DelimiterTest.csv
--boundary--

### Get people
GET {{WebApi_HostAddress}}/api/people
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJkOWRlMDE4ZC0wYTYzLTRhYjEtODc4ZC05ZTgxMDhhN2Q0YmYiLCJpYXQiOiIxNzc5OTkzOTk0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc5OTkzOTk0LCJleHAiOjE3Nzk5OTc1OTQsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.uWZRkDI1695tzOHqkA1VkhRWQBv0QtTWvfaIq3q4lkE

### Get companies
GET {{WebApi_HostAddress}}/api/companies
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJhZWM2MzkzZC0yMjI2LTQ5ZGEtYjJjYi1lMmM1NmViOWNjYTkiLCJpYXQiOiIxNzc3NzIzNzY4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc3NzIzNzY4LCJleHAiOjE3Nzc3MjczNjgsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.xgB8jxWiSFSn_XJ4K8wkaeDSlqv-9FUNts4hcwO-9lE

### Get organizations
GET {{WebApi_HostAddress}}/api/organizations
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiJhZWM2MzkzZC0yMjI2LTQ5ZGEtYjJjYi1lMmM1NmViOWNjYTkiLCJpYXQiOiIxNzc3NzIzNzY4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc3NzIzNzY4LCJleHAiOjE3Nzc3MjczNjgsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.xgB8jxWiSFSn_XJ4K8wkaeDSlqv-9FUNts4hcwO-9lE
